import java.util.ArrayList;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers. 
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 * @author Administrator
 *
 */
public class Prob12 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		for(int i =7;;i++){
			if(calDivisors(generateTriangle(i))>500){
				System.out.println(i);
				System.out.println(generateTriangle(i));
				break;
			}
			//System.out.println(i);
		}
	}
	
	public static int generateTriangle(int order){
		int sum=0;
		for(int i =1;i<=order;i++){
			sum+=i;
		}
		return sum;		
	}
	
	public static int calDivisors(int n){
		ArrayList<Integer> primes=EratosthenesSieve.runEratosthenesSieve((int)Math.sqrt(n));
		int product=1;
		int temp=0;
		for(int i=0;i<primes.size();i++){
			temp=0;
			while(n%primes.get(i) == 0){
				n/=primes.get(i);
				temp++;
			}
			product=product*(temp+1);
		}
		return product;
	}
}
