//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed 4000000, 
//find the sum of the even-valued terms.
public class Prob02 {

	static int first = 1;
	 static int second = 2;

	public static void main(String[] args) {
		int sum = 0;
		for(;second<=4000000;){
			if(second%2==0){
				sum+=second;
			}
			System.out.println(nextFab());
		}
		System.out.println(sum);

	}
	private static int nextFab(){
		int temp = first + second;
		first = second;
		second = temp;
		return temp;	
	}

}
